language: scala
sudo: required
dist: trusty

git:
  depth: 9999

scala:
  - 2.11.12
  - 2.12.9
  - 2.13.0

jdk: openjdk8

before_install: export PATH=${PATH}:./vendor/bundle

install:
  - set -e

  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - cd ~/.nvm
  - git checkout `git describe --abbrev=0 --tags`
  - cd -

  - source ~/.nvm/nvm.sh
  - nvm install $TRAVIS_NODE_VERSION

  - pip install --user codecov
  - gem install jekyll -v 2.5

script:
  - set -e
  - $SBT ++$TRAVIS_SCALA_VERSION validateJS coverage validateJVM coverageReport
  - codecov

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2d5ea16a2f66f60a590b
    on_success: change
    on_failure: always
    on_start: false

env:
  global:
    - 'SBT="$(pwd)/sbt"'
    - TRAVIS_NODE_VERSION="4"

cache:
  directories:
    - "$HOME/.sbt/boot/scala*"
    - "$HOME/.sbt/launchers"
    - "$HOME/.ivy2/cache"
    - "$HOME/.nvm"

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
